### ISSUE TITLE
Ongelma buildaamisessa

### ISSUE THREAD

**Issue by mluukkai** [Nelarius/Miinaharava#1]
lisäys allaolevaan: buildi toimiikin työkoneella, molemmat saman distribuution linuxeja. en nyt kuitenkaan jää tutkimaan ongelmaa.
# 

Ilmeni allaoleva ongelma. Mitenkähän tämä ratkeaisi, googlekaan ei oikein osannut auttaa. 

mluukkai@e42-17:~/Miinaharava$ ./build.sh 
mkdir: cannot create directory `build': File exists
/home/mluukkai/Miinaharava/src
Found SFML: /home/mluukkai/Miinaharava/sfml/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mluukkai/Miinaharava/build
Linking CXX executable Miinaharava
../sfml/lib/libsfml-graphics.so: undefined reference to`jpeg_finish_compress@LIBJPEG_6.2'
../sfml/lib/libsfml-graphics.so: undefined reference to `jpeg_write_scanlines@LIBJPEG_6.2'
../sfml/lib/libsfml-graphics.so: undefined reference to`jpeg_std_error@LIBJPEG_6.2'
../sfml/lib/libsfml-graphics.so: undefined reference to `jpeg_set_quality@LIBJPEG_6.2'
../sfml/lib/libsfml-graphics.so: undefined reference to`jpeg_set_defaults@LIBJPEG_6.2'
../sfml/lib/libsfml-graphics.so: undefined reference to `jpeg_CreateCompress@LIBJPEG_6.2'
../sfml/lib/libsfml-graphics.so: undefined reference to`jpeg_start_compress@LIBJPEG_6.2'
../sfml/lib/libsfml-graphics.so: undefined reference to `jpeg_destroy_compress@LIBJPEG_6.2'
../sfml/lib/libsfml-graphics.so: undefined reference to`jpeg_stdio_dest@LIBJPEG_6.2'
collect2: ld returned 1 exit status
make[2]: **\* [Miinaharava] Error 1
make[1]: **\* [CMakeFiles/Miinaharava.dir/all] Error 2
make: **\* [all] Error 2

**Comment by mluukkai** [comment]
lisäys edelliseen: 

buildi toimiikin työkoneella, molemmat saman distribuution linuxeja. en nyt kuitenkaan jää tutkimaan ongelmaa.

**Comment by Nelarius** [comment]
Kummallinen ongelma tosiaan, etenkin kun googlestakaan ei oikein löydy apua.. :/ Toivottavasti bildaaminen toimii kuitenkin jatkossakin työkoneellasi.
